name: Create release with ZIP
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Get Version
        id: version
        uses: howbout-ltd/get-xml-info@master
        with:
          xml-file: "addon.xml"
          xpath: "//addon/@version"
      - name: Get changelog
        id: changelog
        uses: howbout-ltd/get-xml-info@master
        with:
          xml-file: "addon.xml"
          xpath: "//addon/extension[2]/news"
      - name: Archive Release
        uses: thedoctor0/zip-release@master
        with:
          type: 'zip'
          path: 'plugin.video.filmin'
          directory: '..'
          filename: 'filmin-kodi-release.zip'
          exclusions: '*.git* .editorconfig'
      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "../filmin-kodi-release.zip"
          artifactContentType: application/zip
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: v${{ steps.version.outputs.info }}
          body: ${{ steps.changelog.outputs.info }}
          skipIfReleaseExists: true
