name: Create ZIP
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Get XML
        id: getxml
        uses: mavrosxristoforos/get-xml-info@1.0
        with:
          xml-file: "addon.xml"
          xpath: "//addon"
      - name: Archive Release
        uses: thedoctor0/zip-release@master
        with:
          type: 'zip'
          filename: 'filmin-kodi-release.zip'
          exclusions: '*.git* .editorconfig'
      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "filmin-kodi-release.zip"
          artifactContentType: application/zip
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: v${{ steps.getxml.outputs.info.version }}
          allowUpdates: true
